apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: {{ .Values.secret.type }}
data:
  pictrs__api_key: "api_key" #base64 encoded api key