apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: {{ .Values.secret.type }}
stringData:
  pictrs__api_key: {{ .Values.secret.data.api_key }}