apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secret
    namespace: {{ .Values.namespace }}
type: {{ .Values.secret.type }}
stringData:
    postgres-password: {{ .Values.secret.data.postgres-password }}
    pgadmin-default-email: {{ .Values.secret.data.pgadmin-default-email }}
    pgadmin-default-password: {{ .Values.secret.data.pgadmin-default-password }}