apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secret
    namespace: {{ .Values.namespace }}
type: {{ .Values.secret.type }}
data:
    postgres-password: "password" #base64 encoded password
    pgadmin-default-email: "mail@lemmy.example" #base64 encoded mail
    pgadmin-default-password: "password" #base64 encoded password