apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-pa
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.service_pa.port }}
      protocol: {{ .Values.service_pa.protocol }}
      targetPort: {{ .Values.service_pa.targetPort }}
  selector:
    app: {{ .Release.Name }}-pa