apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.deployment.replicaCount }}
  serviceName: {{ .Release.Name }}-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: {{ .Values.service.port }}
              name: {{ .Release.Name }}-port
          env:
          - name: RUST_BACKTRACE
            value: {{ .Values.deployment.env.rust_backtrace | quote }}
          - name: RUST_LOG
            value: "warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_queries=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
          volumeMounts:
          - name: {{ .Release.Name }}-configmap
            mountPath: "/config"
            readOnly: true
      volumes:
        - name: {{ .Release.Name }}-configmap
          configMap:
            name: {{ .Release.Name }}-configmap