apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-ui
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ui
  replicas: {{ .Values.deployment_ui.replicaCount }}
  serviceName: {{ .Release.Name }}-service-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ui
    spec:
      terminationGracePeriodSeconds: {{ .Values.deployment_ui.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Release.Name }}-ui
          image: {{ .Values.image_ui.repository }}
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: {{ .Values.service_ui.port }}
              name: {{ .Release.Name }}-port
          env:
          - name: LEMMY_UI_LEMMY_EXTERNAL_HOST
            value: {{ .Values.deployment_ui.env.lemmy_ui_lemmy_external_host | quote }}
          - name: LEMMY_UI_LEMMY_INTERNAL_HOST
            value: {{ .Values.deployment_ui.env.lemmy_ui_lemmy_internal_host | quote }}
          - name: LEMMY_HTTPS
            value: {{ .Values.deployment_ui.env.lemmy_https | quote }}
          - name: LEMMY_UI_DEBUG
            value: {{ .Values.deployment_ui.env.lemmy_ui_debug | quote }}